"""Golden test for the scan -> raw + aggregate() refactor (issue #5).

Replays a deterministic, fixed-date fixture through the CURRENT scan()/
aggregate() and asserts the all-time payload equals the pre-HUD, pre-refactor
(commit 4c8ca5c, i.e. main before v0.4.0) implementation's output — the
contractual "no-params must reproduce the pre-refactor payload" guarantee.

The golden file (tests/golden_alltime.json) was generated by running the
pre-refactor server against this same fixture:

    python3 tests/test_golden.py --gen

Volatile fields (generated_at, scan_ms, db path) are stripped on both sides.
4c8ca5c predates the v0.4.0 HUD, so the golden lacks recent_tps /
recent_tps_avg10 / recent_in_progress (dropped from the current side before
comparing); it DOES carry median_tps (computed from the old all_tps), which
stays on both sides as a real equivalence assertion.

Fixture constraints keep the golden time-invariant forever:
  * all turns strictly in the past (latest date far before "today" and
    before "yesterday") -> streaks.current is always 0
  * no compaction markers -> compactions_14d / compactions_prev_14d always 0
  * no in-progress turns
  * no today session

Intentional deviations from the 4c8ca5c baseline (v0.5.1, issues #6-#12) —
the golden carries these on purpose; do NOT re-run --gen after they land
(--gen would regenerate from the pre-refactor code and re-introduce the old
strings):
  * insights: full weekday names -> "Peak hours: on Monday around 21:00 ..."
  * insights: new API-error-class insight ("API errors: 1 failed turn ...")
  * context.bins: last bin labeled "128k+" (was "128k-infk")
"""

import importlib.util
import json
import os
import sqlite3
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from opencode_deck import server  # noqa: E402

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golden_alltime.json")
OLD_SERVER_REF = "4c8ca5c"
# Keys introduced by v0.4.0 (5609717) that have no pre-refactor counterpart.
# median_tps is NOT in this set: it existed before (computed from all_tps) and
# must stay on both sides as a real equivalence assertion.
HUD_NEW_KEYS = ("recent_tps", "recent_tps_avg10", "recent_in_progress")


def _ts(y, mo, d, h, mi):
    return int(datetime(y, mo, d, h, mi).replace(tzinfo=None).timestamp() * 1000)


def build_golden_fixture(path):
    """Fixed-date (Jul–Aug 2026) fixture: 2 models, 3 agents, tools (ok/err/
    pending/orphan), cache reads, missing-completed, sub-second and >1h
    exclusions, errored turn, malformed JSON skip. No compactions, no
    in-progress turns, nothing near today."""
    conn = sqlite3.connect(path)
    conn.executescript("""
    CREATE TABLE session (
      id TEXT, project_id TEXT, workspace_id TEXT, parent_id TEXT, slug TEXT,
      directory TEXT, path TEXT, title TEXT, version TEXT, share_url TEXT,
      summary_additions INTEGER, summary_deletions INTEGER, summary_files INTEGER,
      summary_diffs TEXT, metadata TEXT, cost REAL,
      tokens_input INTEGER, tokens_output INTEGER, tokens_reasoning INTEGER,
      tokens_cache_read INTEGER, tokens_cache_write INTEGER,
      revert TEXT, permission TEXT, agent TEXT, model TEXT,
      time_created INTEGER, time_updated INTEGER, time_compacting INTEGER,
      time_archived INTEGER
    );
    CREATE TABLE message (
      id TEXT, session_id TEXT, time_created INTEGER, time_updated INTEGER, data TEXT
    );
    CREATE TABLE part (
      id TEXT, message_id TEXT, session_id TEXT, time_created INTEGER,
      time_updated INTEGER, data TEXT
    );
    """)
    conn.execute("PRAGMA journal_mode=WAL")

    m_a = json.dumps({"id": "test-27b", "providerID": "vader", "variant": "default"})
    m_b = json.dumps({"id": "gpt-x", "providerID": "openai", "variant": ""})

    sessions = [
        # sid, parent, directory, title, agent, model, tin, tout, tr, tcr, tcw, t0, t1
        ("s1", None, "/home/derek/blog", "Golden blog", "build", m_a,
         0.0, 120000, 2500, 300, 200000, 1000, _ts(2026, 7, 20, 21, 0), _ts(2026, 7, 20, 21, 40)),
        ("s2", "s1", "/home/derek/blog", "Golden subagent", "general", m_a,
         0.0, 30000, 100, 0, 50000, 500, _ts(2026, 7, 20, 21, 10), _ts(2026, 7, 20, 21, 20)),
        ("s3", None, "/home/derek/projects", "Golden project", "Assistant", m_b,
         0.0, 80000, 1500, 50, 0, 200, _ts(2026, 7, 21, 9, 0), _ts(2026, 7, 21, 9, 30)),
        ("s4", None, "/home/derek/writing", "Golden writing", "build", m_a,
         0.0, 50000, 200, 0, 40000, 1000, _ts(2026, 8, 1, 10, 0), _ts(2026, 8, 1, 15, 0)),
        ("s5", None, "/home/derek/writing", "Golden recent", "build", m_b,
         0.0, 20000, 50, 0, 20000, 500, _ts(2026, 8, 27, 12, 0), _ts(2026, 8, 27, 12, 5)),
    ]
    for sid, parent, d, title, agent, m, cost, ti, to, tr, tc, tw, t0, t1 in sessions:
        conn.execute(
            "INSERT INTO session (id, parent_id, directory, title, agent, model, "
            "cost, tokens_input, tokens_output, tokens_reasoning, tokens_cache_read, "
            "tokens_cache_write, time_created, time_updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (sid, parent, d, title, agent, m, cost, ti, to, tr, tc, tw, t0, t1))

    def msg(mid, sid, t0, t1, payload):
        conn.execute("INSERT INTO message VALUES (?,?,?,?,?)", (mid, sid, t0, t1, json.dumps(payload)))

    def part(pid, mid, sid, t0, t1, data):
        conn.execute("INSERT INTO part VALUES (?,?,?,?,?,?)", (pid, mid, sid, t0, t1, json.dumps(data)))

    # s1 (test-27b @ vader): 21:00 turn, 500 out, 30s wall, 6s tools -> pure 24s ~ 20.8 tps
    c1 = _ts(2026, 7, 20, 21, 0)
    msg("m1", "s1", c1, c1 + 30000, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 40000, "output": 500, "reasoning": 200, "cache": {"read": 150000, "write": 1000}},
        "cost": 0, "time": {"created": c1, "completed": c1 + 30000}})
    part("p1", "m1", "s1", c1, c1 + 6000, {
        "type": "tool", "tool": "bash", "callID": "c1",
        "state": {"status": "completed", "time": {"start": c1 + 1000, "end": c1 + 4000}}})
    part("p2", "m1", "s1", c1, c1 + 6000, {
        "type": "tool", "tool": "bash", "callID": "c2",
        "state": {"status": "completed", "time": {"start": c1 + 4000, "end": c1 + 6000}}})
    # 21:20 turn, 300 out, 10s -> pure 10s = 30 tps
    c2 = _ts(2026, 7, 20, 21, 20)
    msg("m2", "s1", c2, c2 + 10000, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 20000, "output": 300, "reasoning": 0, "cache": {"read": 10000, "write": 0}},
        "cost": 0, "time": {"created": c2, "completed": c2 + 10000}})
    # 21:30 completed missing (excluded from tps, counts as turn)
    c3 = _ts(2026, 7, 20, 21, 30)
    msg("m3", "s1", c3, c3, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 5000, "output": 10, "reasoning": 0, "cache": {"read": 0, "write": 0}},
        "cost": 0, "time": {"created": c3}})
    # user message (skipped) + malformed JSON (skipped)
    msg("m4", "s1", c1, c1, {"role": "user", "agent": "build", "time": {"created": c1}})
    conn.execute("INSERT INTO message VALUES (?,?,?,?,?)", ("m5", "s1", c1, c1, "{not json"))
    # orphan tool part referencing a missing message
    part("p9", "mX", "s1", c1, c1 + 60000, {
        "type": "tool", "tool": "bash", "callID": "c9",
        "state": {"status": "completed", "time": {"start": c1, "end": c1 + 60000}}})

    # s2 (subagent): 10s turn, 450 out -> 45 tps
    c6 = _ts(2026, 7, 20, 21, 10)
    msg("m6", "s2", c6, c6 + 10000, {
        "role": "assistant", "agent": "general", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 8000, "output": 450, "reasoning": 0, "cache": {"read": 20000, "write": 0}},
        "cost": 0, "time": {"created": c6, "completed": c6 + 10000}})

    # s3 (gpt-x @ openai): 9:00 sub-second pure (excluded), 9:10 errored, 9:20 300 out / 5s = 60 tps
    c7 = _ts(2026, 7, 21, 9, 0)
    msg("m7", "s3", c7, c7 + 2000, {
        "role": "assistant", "agent": "Assistant", "modelID": "gpt-x", "providerID": "openai",
        "tokens": {"input": 70000, "output": 15, "reasoning": 0, "cache": {"read": 100, "write": 0}},
        "cost": 0, "time": {"created": c7, "completed": c7 + 2000}})
    part("p3", "m7", "s3", c7, c7 + 1700, {
        "type": "tool", "tool": "read", "callID": "c3",
        "state": {"status": "completed", "time": {"start": c7 + 200, "end": c7 + 1700}}})
    c8 = _ts(2026, 7, 21, 9, 10)
    msg("m8", "s3", c8, c8 + 500, {
        "role": "assistant", "agent": "Assistant", "modelID": "gpt-x", "providerID": "openai",
        "tokens": {"input": 1000, "output": 0, "reasoning": 0, "cache": {"read": 0, "write": 0}},
        "error": {"name": "APIError", "data": {"message": "not found", "statusCode": 404,
             "metadata": {"url": "http://192.0.2.42:4242/chat/completions"}}},
        "time": {"created": c8, "completed": c8 + 500}})
    part("p4", "m8", "s3", c8, c8, {
        "type": "tool", "tool": "webfetch", "callID": "c4",
        "state": {"status": "error", "time": {}}})
    c9 = _ts(2026, 7, 21, 9, 20)
    msg("m9", "s3", c9, c9 + 5000, {
        "role": "assistant", "agent": "Assistant", "modelID": "gpt-x", "providerID": "openai",
        "tokens": {"input": 30000, "output": 300, "reasoning": 0, "cache": {"read": 0, "write": 0}},
        "cost": 0, "time": {"created": c9, "completed": c9 + 5000}})
    # pending tool (no times)
    part("p5", "m9", "s3", c9, c9, {
        "type": "tool", "tool": "glob", "callID": "c5",
        "state": {"status": "pending", "time": {}}})

    # s4: 10:00 600 out/60s = 10 tps; 11:00 >3600s excluded; 13:00 200 out/20s = 10 tps
    c10 = _ts(2026, 8, 1, 10, 0)
    msg("m10", "s4", c10, c10 + 60000, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 60000, "output": 600, "reasoning": 0, "cache": {"read": 200000, "write": 0}},
        "cost": 0, "time": {"created": c10, "completed": c10 + 60000}})
    c11 = _ts(2026, 8, 1, 11, 0)
    msg("m11", "s4", c11, c11 + 3700000, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 90000, "output": 1000, "reasoning": 0, "cache": {"read": 0, "write": 0}},
        "cost": 0, "time": {"created": c11, "completed": c11 + 3700000}})
    c12 = _ts(2026, 8, 1, 13, 0)
    msg("m12", "s4", c12, c12 + 20000, {
        "role": "assistant", "agent": "build", "modelID": "test-27b", "providerID": "vader",
        "tokens": {"input": 15000, "output": 200, "reasoning": 0, "cache": {"read": 0, "write": 0}},
        "cost": 0, "time": {"created": c12, "completed": c12 + 20000}})

    # s5 (gpt-x, recent-ish but not yesterday/today): 90 out/30s = 3 tps
    c13 = _ts(2026, 8, 27, 12, 0)
    msg("m13", "s5", c13, c13 + 30000, {
        "role": "assistant", "agent": "build", "modelID": "gpt-x", "providerID": "openai",
        "tokens": {"input": 12000, "output": 90, "reasoning": 0, "cache": {"read": 20000, "write": 0}},
        "cost": 0, "time": {"created": c13, "completed": c13 + 30000}})

    conn.commit()
    conn.close()


def _strip_volatile(p, v40=False):
    """Drop the inherently time-based / machine-dependent fields.

    With v40=True (current implementation) also drop the keys introduced by
    the v0.4.0 HUD commit, which the 4c8ca5c golden does not have."""
    p = dict(p)
    p.pop("generated_at", None)
    p.pop("scan_ms", None)
    p["db"] = "<db>"
    if v40:
        for k in HUD_NEW_KEYS:
            p.pop(k, None)
    return p


def _load_old_server(old_src):
    fd, path = tempfile.mkstemp(suffix=".py")
    with os.fdopen(fd, "w") as f:
        f.write(old_src)
    try:
        spec = importlib.util.spec_from_file_location("server_old", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    finally:
        os.unlink(path)


def generate_golden():
    """Run the PRE-REFACTOR (4c8ca5c) scan() over the fixture and write the golden."""
    old_src = subprocess.run(
        ["git", "show", f"{OLD_SERVER_REF}:opencode_deck/server.py"],
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        capture_output=True, text=True, check=True).stdout
    old = _load_old_server(old_src)
    tmp = tempfile.TemporaryDirectory()
    db = os.path.join(tmp.name, "opencode.db")
    build_golden_fixture(db)
    payload = old.scan(db)
    tmp.cleanup()
    golden = _strip_volatile(payload)
    with open(GOLDEN, "w") as f:
        json.dump(golden, f, indent=1, sort_keys=True)
        f.write("\n")
    print(f"wrote {GOLDEN}")


class TestGoldenAllTime(unittest.TestCase):
    def test_all_time_matches_pre_refactor(self):
        import opencode_deck.server as cur
        with tempfile.TemporaryDirectory() as tmp:
            db = os.path.join(tmp, "opencode.db")
            build_golden_fixture(db)
            raw = cur.scan(db)
            payload = cur.aggregate(raw, None, None)
        actual = _strip_volatile(payload, v40=True)
        with open(GOLDEN) as f:
            expected = json.load(f)
        if actual != expected:
            diff = {}
            for k in set(actual) | set(expected):
                if actual.get(k) != expected.get(k):
                    diff[k] = {"actual": actual.get(k), "expected": expected.get(k)}
            self.fail("all-time payload differs from pre-refactor golden:\n"
                      + json.dumps(diff, indent=1, default=str)[:4000])
        self.assertIsInstance(payload["recent_tps"], list)
        # no-params must not window anything
        self.assertEqual(payload["streaks"]["current"], 0)


if __name__ == "__main__":
    if "--gen" in sys.argv:
        generate_golden()
        sys.exit(0)
    unittest.main()
